"""empty message

Revision ID: 5426b0eb2cf9
Revises: 72bd34a9f5d7
Create Date: 2025-05-04 22:27:34.613406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5426b0eb2cf9'
down_revision = '72bd34a9f5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('American', sa.String(length=30), nullable=False),
    sa.Column('Chinese', sa.String(length=30), nullable=False),
    sa.Column('Jamacian', sa.String(length=30), nullable=False),
    sa.Column('Indian', sa.String(length=30), nullable=False),
    sa.Column('Italian', sa.String(length=30), nullable=False),
    sa.Column('French', sa.String(length=30), nullable=False),
    sa.Column('Japanese', sa.String(length=30), nullable=False),
    sa.Column('Korean', sa.String(length=30), nullable=False),
    sa.Column('Mexican', sa.String(length=30), nullable=False),
    sa.Column('Thai', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cooking_fequency', sa.Integer(), nullable=False),
    sa.Column('allergies', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('gardening', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('zip', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zip')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('user_habits')
    op.drop_table('cuisine')
    # ### end Alembic commands ###
